version: '3'

tasks:
  gen-proto:
    desc: Generate Go files from .proto using protoc
    cmds:
      - |
        protoc -I ../proto \
        ../proto/todo.proto \
        --go_out=./gen \
        --go_opt=paths=source_relative \
        --go-grpc_out=./gen/ \
        --go-grpc_opt=paths=source_relative \
        --validate_out="lang=go:."
    sources:
      - proto/todo.proto
    generates:
      - gen/todo.pb.go
      - gen/todo_grpc.pb.go